### ISSUE TITLE
Docs TODO

### ISSUE THREAD

**Issue by Whimfoome** [inventory-oasis/inventory-oasis.github.io#2]
- [x] Code Overview Diagram
  - Inventory Component attached to a scene with it's parameters/data
  - ToggleInventory Example calling:
  - Inventory Window, which instantiates Inventory Slots
  - Each Inventory Slot points to the inv component resource at specific index
- [x] Page about Inventory Component
- [x] Page about Item Resources and Uses
  - Creating new Items
- [x] Page about Inventory Window
- [x] Page about Inventory Slots
- [x]  Introductory Page with the diagram, showcasing the examples, explaining some things
- [x] Examples Page
